name: medparswell
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - fastapi
  - uvicorn
  - pydantic
  - httpx
  - scikit-learn
  - spacy
  - pydantic-settings
  - pip:
      - python-multipart
      - llama-cpp-python