name: medparswell
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - fastapi
  - uvicorn
  - pydantic
  - httpx
  - scikit-learn
  - spacy
  - pydantic-settings
  - python-dotenv
  - pytest
  - pytest-asyncio
  - cmake
  - make
  - mypy
  - black
  - isort
  - pip:
      - python-multipart
      - llama-cpp-python